services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=moneydb
      - DB_USER=devkonrad
      - DB_PASS=2003kk
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=moneydb
      - POSTGRES_USER=devkonrad
      - POSTGRES_PASSWORD=2003kk

volumes:
  dev-db-data: