# Generated by Django 3.2.25 on 2024-09-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accounthistory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
