# Generated by Django 3.2.25 on 2024-09-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240923_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounthistory',
            options={'verbose_name': 'Account history', 'verbose_name_plural': 'Accounts history'},
        ),
    ]
