---
  name: Checks # Workflow name
  
  on: [push] # Trigger workflow on push events
  
  jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USER }} # Docker Hub username from GitHub secrets
            password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub token from GitHub secrets
        - name: Checkout
          uses: actions/checkout@v2 # Check out the code from the repository
        - name: Test
          run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
        - name: Lint
          run: docker compose run --rm app sh -c "flake8"